plugins {
    id 'com.android.application'
}

android {
    namespace 'com.deepurang.aiquizbattle'
    compileSdk 36

    defaultConfig {
        applicationId 'com.deepurang.aiquizbattle'
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }
}

dependencies {
    implementation 'com.google.android.libraries.ads.mobile.sdk:ads-mobile-sdk:1.4.0'
}
